[platformio]
default_envs = gladiator_c6

[env:gladiator_c6]
platform = espressif32@7.0.1
board = seeed_xiao_esp32c6
framework = espidf
board_build.partitions = partitions.csv
upload_port = COM30
upload_speed = 460800
monitor_port = COM30
monitor_speed = 115200
build_flags = -I../shared
