#pragma once
static const char GATEWAY_PAGE[]=R"HTML(<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gladiator · Development</title>
<style>:root{color-scheme:dark;font-family:system-ui}*{box-sizing:border-box}body{background:#0c131a;color:#eaf1f5;margin:0}main{max-width:1160px;margin:auto;padding:28px}header,.row{display:flex;justify-content:space-between;align-items:center;gap:15px}h1{margin-bottom:4px}h2{font-size:20px}p,small{color:#a6b8c4}a{color:#82d6ec}nav{display:flex;gap:8px;flex-wrap:wrap;margin:24px 0}button,input{font:inherit;border-radius:8px;padding:10px;border:1px solid #3b5262}button{cursor:pointer;background:#213643;color:white}button[aria-selected=true]{background:#94d3df;color:#10222b}input{display:block;width:100%;background:#101d27;color:white;margin:8px 0 15px}section,article{background:#17232d;padding:20px;border-radius:12px;margin-bottom:16px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px}.metric{font-size:30px;font-weight:650}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#0e1921;padding:15px;border-radius:8px;max-height:65vh;overflow:auto;font-size:12px}details{border-top:1px solid #344650;padding:14px 0}summary{cursor:pointer}output{display:block;margin:12px 0;color:#f1bf68}[hidden]{display:none!important}.badge{border:1px solid #436574;border-radius:30px;padding:8px 14px}.warn{color:#f1bf68}label{display:block}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:12px 8px;border-bottom:1px solid #344650}@media(max-width:600px){main{padding:16px}header{align-items:start}table{font-size:12px}}</style>
<main><header><div><h1>Gladiator</h1><small>Interface v1 · Development · S3 authority</small></div><a href="/">Open field controls ↗</a></header><nav role="tablist" aria-label="Development views"><button role="tab" id="tab-overview" aria-controls="overview" data-tab="overview" aria-selected="true">Overview</button><button role="tab" id="tab-controller" aria-controls="controller" data-tab="controller" aria-selected="false">Controller</button><button role="tab" id="tab-power" aria-controls="power" data-tab="power" aria-selected="false">Power</button><button role="tab" id="tab-imu" aria-controls="imu" data-tab="imu" aria-selected="false">IMU</button><button role="tab" id="tab-range" aria-controls="range" data-tab="range" aria-selected="false">Range</button><button role="tab" id="tab-presence" aria-controls="presence" data-tab="presence" aria-selected="false">Presence</button><button role="tab" id="tab-communications" aria-controls="communications" data-tab="communications" aria-selected="false">Communications</button><button role="tab" id="tab-system" aria-controls="system" data-tab="system" aria-selected="false">System</button><button role="tab" id="tab-logs" aria-controls="logs" data-tab="logs" aria-selected="false">Logs</button><button role="tab" id="tab-firmware" aria-controls="firmware" data-tab="firmware" aria-selected="false">Firmware</button></nav>
<div id="overview" role="tabpanel"><section><div class="row"><h2>S3 robot state</h2><span id="live" class="badge">Waiting</span></div><div class="grid"><div><small>Controller</small><div id="state" class="metric">UNKNOWN</div></div><div><small>Transport</small><div id="transport" class="metric">—</div></div><div><small id="powerSource">Battery</small><div id="volts" class="metric">—</div></div><div><small>Current</small><div id="amps" class="metric">—</div></div></div><p>The S3 owns motor outputs, safety, sensors and robot decisions. This C6 exposes communications and diagnostics.</p></section><section><h2>Sensor health</h2><table><thead><tr><th>Sensor</th><th>Health</th><th>Sampling</th><th>Sample age</th></tr></thead><tbody id="health"></tbody></table><p id="age"></p></section></div>
<div id="controller" role="tabpanel" hidden><section><h2>Controller</h2><p>S3 owns arming, motor outputs and control sessions. Switching away disarms this test session. Diagnostics in the controls includes independent track testing.</p><button id="openControls">Open test controls</button><iframe id="testControls" title="S3-authorized test controls" hidden style="width:100%;height:1100px;border:0" ></iframe><details><summary>S3 controller / ownership / native values</summary><pre id="controlJson">Waiting</pre></details></section></div>
<div id="power" role="tabpanel" hidden><section><h2>Power · INA226</h2><p id="status-power">UNKNOWN</p><div id="values-power" class="grid"></div><p>Values and health are reported by S3. Native data is a separately requested snapshot.</p><button data-inspect>Inspect for 30 seconds</button><details><summary>Native / raw data, configuration and timestamps</summary><pre id="sensor-power">No detail requested</pre></details></section></div>
<div id="imu" role="tabpanel" hidden><section><h2>IMU · BNO085</h2><p id="status-imu">UNKNOWN</p><div id="values-imu" class="grid"></div><p>Values and health are reported by S3. Native data is a separately requested snapshot.</p><button data-inspect>Inspect for 30 seconds</button><details><summary>Native / raw data, configuration and timestamps</summary><pre id="sensor-imu">No detail requested</pre></details></section></div>
<div id="range" role="tabpanel" hidden><section><h2>Range · SEN0628</h2><p id="status-tofFront">UNKNOWN</p><div id="values-tofFront" class="grid"></div><p>Values and health are reported by S3. Native data is a separately requested snapshot.</p><button data-inspect>Inspect for 30 seconds</button><details><summary>Native / raw data, configuration and timestamps</summary><pre id="sensor-tofFront">No detail requested</pre></details><details><summary>Native 8 × 8 range grid (mm, device order)</summary><p id="gridAge"></p><div id="rangeGrid" style="display:grid;grid-template-columns:repeat(8,minmax(0,1fr));gap:4px"></div></details></section></div>
<div id="presence" role="tabpanel" hidden><section><h2>Presence · C4001</h2><p id="status-presence">UNKNOWN</p><div id="values-presence" class="grid"></div><p>Values and health are reported by S3. Native data is a separately requested snapshot.</p><button data-inspect>Inspect for 30 seconds</button><details><summary>Native / raw data, configuration and timestamps</summary><pre id="sensor-presence">No detail requested</pre></details></section></div>
<div id="communications" role="tabpanel" hidden><section><h2>Gladiator Link</h2><p>UART is preferred after five seconds of stable two-way communication. Sustained UART loss uses the C6 field AP for both the S3 link and phone access.</p><p id="linkSummary"></p><details><summary>Native link diagnostics</summary><pre id="linkJson"></pre></details><button id="ping">Ping S3</button> <button id="bulk">Request Wi-Fi bandwidth for 60 seconds</button><output id="linkReply"></output></section><section><h2>Radio & network</h2><p id="networkSummary"></p><details><summary>Native network diagnostics</summary><pre id="radioJson"></pre></details><details><summary>Connect to a Wi-Fi network</summary><p>The field AP stays available while C6 connects to your 2.4 GHz network.</p><form id="wifiForm"><label>Network name<input id="ssid" maxlength="32" required></label><label>Wi-Fi password<input id="password" type="password" minlength="8" maxlength="63" required></label><button>Save and connect</button></form><output id="wifiReply"></output></details><p>BLE and 802.15.4 are extension points on the C6; this firmware uses Wi-Fi and UART. Existing direct S3 BLE remains available.</p></section></div>
<div id="system" role="tabpanel" hidden><section><h2>System</h2><p>S3 system details arrive with a requested detail stream. Retained logs have their own Logs tab. Each snapshot includes its age.</p><button id="systemInspect">Refresh S3 diagnostics</button><p id="systemSummary"></p><details><summary>S3 native system snapshot</summary><pre id="systemJson"></pre></details><details><summary>C6 complete diagnostics</summary><pre id="gatewayJson"></pre></details></section></div>
<div id="logs" role="tabpanel" hidden><section><h2>Logs</h2><button data-inspect>Refresh S3 logs</button><p id="logAge">No S3 log received</p><label>Filter S3 log<input id="logFilter" placeholder="Filter text"></label><label><input type="checkbox" id="hideSensors" style="display:inline;width:auto" checked> Hide periodic sensor readings</label><pre id="logText"></pre><details><summary>Observed communications events in this browser</summary><pre id="events"></pre></details></section></div>
<div id="firmware" role="tabpanel" hidden><section><h2>Firmware inventory</h2><pre id="firmwareJson"></pre><details><summary>Update C6 firmware</summary><p>Upload the C6 gateway image. The S3 remains responsible for driving and will expire any interrupted remote session.</p><form id="otaForm"><input id="firmwareFile" type="file" accept=".bin" required aria-label="C6 firmware image"><button id="upload">Upload C6 firmware</button></form><output id="otaReply"></output></details><details><summary>S3 firmware & recovery</summary><p>S3 firmware updates use its existing USB or recovery service. Connect to Gladiator-Setup and open <a href="http://192.168.4.1/service">S3 recovery service</a>. That AP opens automatically when C6 communication fails; USB and direct BLE remain available.</p></details></section></div>
<section><output id="detailReply" aria-live="polite"></output><p id="nativeAge">No detail requested</p><details><summary>Diagnostic capture controls</summary><p>Native sensor snapshots, S3 system details and retained logs use an explicit subscription. Snapshot ages remain visible after the lease expires.</p><button id="inspect">Inspect for 30 seconds</button> <button id="stream">Start detail stream</button> <button id="endStream">Stop stream</button><details><summary>Complete native snapshot</summary><pre id="native"></pre></details></details><details><summary>Maintenance access</summary><p>Required for changes, diagnostic subscriptions, field control and updates. Read the key using the C6 USB credentials command. Kept only in this page's memory.</p><label>Maintenance key<input id="key" type="password" maxlength="32" autocomplete="off"></label></details><small id="error" class="warn"></small></section></main>
<script>
const $=id=>document.getElementById(id),show=(id,v)=>$(id).textContent=JSON.stringify(v,null,2);let latest=null,streaming=false,lastEvent='',events=[];
const sensors={power:'Power · INA226',imu:'Orientation · BNO085',tofFront:'Range · SEN0628',presence:'Presence · C4001'};
function stopTest(){const f=$('testControls');if(f.src)f.contentWindow.postMessage({type:'interface-stop'},location.origin);}
function sendKey(){const f=$('testControls');if(f.src)f.contentWindow.postMessage({type:'interface-key',key:$('key').value.trim()},location.origin);}
$('openControls').onclick=()=>{const f=$('testControls');f.hidden=false;if(!f.getAttribute('src'))f.src='/?embedded=1';$('openControls').hidden=true;};
window.addEventListener('message',e=>{if(e.origin===location.origin&&e.source===$('testControls').contentWindow&&e.data?.type==='interface-ready')sendKey();});
$('key').oninput=sendKey;window.addEventListener('blur',()=>{if(document.activeElement!==$('testControls'))stopTest();});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopTest();});
let rawLog='';function renderLogs(){const needle=$('logFilter').value.toLowerCase();$('logText').textContent=rawLog.split('\n').filter(line=>(!$('hideSensors').checked||!/^\[\d+\] (Sensors \||VBUS:)/.test(line))&&line.toLowerCase().includes(needle)).join('\n');}
$('logFilter').oninput=renderLogs;$('hideSensors').onchange=renderLogs;
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{if(b.dataset.tab!=='controller')stopTest();document.querySelectorAll('[data-tab]').forEach(x=>{let selected=x===b;x.tabIndex=selected?0:-1;x.setAttribute('aria-selected',selected);$(x.dataset.tab).hidden=!selected;});});
const tabs=[...document.querySelectorAll('[data-tab]')];tabs.forEach((b,i)=>{b.tabIndex=i===0?0:-1;$(b.dataset.tab).setAttribute('aria-labelledby',b.id);b.onkeydown=e=>{let next=e.key==='ArrowRight'?(i+1)%tabs.length:e.key==='ArrowLeft'?(i+tabs.length-1)%tabs.length:e.key==='Home'?0:e.key==='End'?tabs.length-1:-1;if(next>=0){e.preventDefault();tabs[next].click();tabs[next].focus();}};});
function draw(s){latest=s;const g=s.gateway,r=s.robot||{},fresh=g.robotConnected;
 $('live').textContent=fresh?'Connected':'S3 unavailable';$('state').textContent=fresh?r.controller?.state||'UNKNOWN':'UNKNOWN';$('transport').textContent=fresh?(g.transport||'NONE').toUpperCase():'NONE';
 const p=r.power,powerFresh=fresh&&p?.meta?.health==='OK'&&Number.isFinite(p.meta.ageMs)&&p.meta.ageMs<500&&Number.isFinite(p.derived?.busVolts)&&Number.isFinite(p.derived?.currentAmps);
 $('powerSource').textContent=r.controller?.benchPower?'BENCH':'Battery';$('volts').textContent=powerFresh?p.derived.busVolts.toFixed(2)+' V':'—';$('amps').textContent=powerFresh?p.derived.currentAmps.toFixed(2)+' A':'—';
 $('health').replaceChildren();for(const [key,name] of Object.entries(sensors)){const m=r[key]?.meta,row=$('health').insertRow();for(const v of [name,fresh?m?.health||'UNKNOWN':'UNAVAILABLE',Number.isFinite(m?.rateHz)?m.rateHz.toFixed(1)+' /s':'—',m?.ageMs==null?'—':m.ageMs+' ms'])row.insertCell().textContent=v;show('sensor-'+key,{summary:r[key],native:s.native?.[key]??null,nativeSnapshotAgeMs:s.nativeAgeMs});
 const usable=fresh&&m?.health==='OK'&&Number.isFinite(m?.ageMs)&&m.ageMs<(key==='tofFront'||key==='presence'?1000:500);
 $('status-'+key).textContent=(fresh?m?.health||'UNKNOWN':'UNAVAILABLE')+' · Sample age '+(m?.ageMs??'unknown')+' ms';
 const target=$('values-'+key);target.replaceChildren();
 const d=r[key]?.derived||{},fields={power:[['Voltage','busVolts','V'],['Current','currentAmps','A'],['Power','watts','W'],['Minimum voltage','minimumVolts','V'],['Peak current','peakAbsAmps','A']],imu:[['Roll','rollDeg','°'],['Pitch','pitchDeg','°'],['Heading','yawDeg','°']],tofFront:[['Nearest','nearestMm','mm'],['Usable zones','usableZones','']],presence:[['Target range','rangeMeters','m'],['Target speed','speedMetersPerSecond','m/s']]};
 for(const [label,k,unit] of fields[key]){const cell=document.createElement('div'),caption=document.createElement('small'),value=document.createElement('div');caption.textContent=label;value.className='metric';const valid=usable&&(key==='imu'?(k==='yawDeg'?d.headingValid:d.valid):key==='tofFront'?d.valid:key==='presence'?d.targetValid:true);value.textContent=valid&&Number.isFinite(d[k])?Number(d[k]).toFixed(k==='nearestMm'||k==='usableZones'?0:2)+' '+unit:'—';cell.append(caption,value);target.append(cell);}
 if(key==='power')$('status-'+key).textContent+=' · Battery '+(fresh?r.controller?.battery||'UNKNOWN':'UNKNOWN');
 if(key==='presence')$('status-'+key).textContent+=' · '+(usable&&d.presenceValid?(d.present?'PRESENT':'CLEAR'):'UNKNOWN');
 if(key==='imu')$('status-'+key).textContent+=' · '+(usable&&d.headingValid?'Heading valid':'Heading unavailable / uncalibrated');}
 $('age').textContent='Controller telemetry age: '+(g.telemetryAgeMs??'unknown')+' ms. Sensor ages advance independently.';
 show('controlJson',r.controller);show('native',s.native);$('nativeAge').textContent=s.nativeAgeMs==null?'No native snapshot received':'Native snapshot received '+s.nativeAgeMs+' ms ago. Values and internal ages describe that snapshot.';
 show('linkJson',Object.fromEntries(['interface','transport','protocolVersion','uartAlive','uartStable','wifiLinkAlive','fieldRecovery','wifiLeaseMs','rxFrames','txFrames','frameErrors','detailErrors','drops','pongs','peerBootId'].map(k=>[k,g[k]])));
 show('radioJson',Object.fromEntries(['antenna','wifiConnected','wifiSsid','ip','rssi','apSsid','apIp','disconnectReason','futureCapabilities'].map(k=>[k,g[k]])));
 show('systemJson',{s3:s.system,receivedAgeMs:s.systemAgeMs,logAgeMs:s.logAgeMs});show('gatewayJson',g);rawLog=s.logs||s.system?.logTail||'Request S3 diagnostics to read its retained log.';renderLogs();$('logAge').textContent='S3 log snapshot age: '+(s.logAgeMs??s.systemAgeMs??'unknown')+' ms';
 $('linkSummary').textContent='Active transport '+(fresh?(g.transport||'NONE').toUpperCase():'NONE')+' · S3 '+(fresh?'CONNECTED':'UNAVAILABLE');
 $('networkSummary').textContent='Field network '+(g.apSsid||'UNKNOWN')+' · Station '+(g.wifiConnected?'CONNECTED':'DISCONNECTED');
 $('systemSummary').textContent=s.system?'S3 '+(s.system.firmware||'UNKNOWN')+' · Reset '+(s.system.resetReason||'UNKNOWN')+' · Snapshot age '+(s.systemAgeMs??'unknown')+' ms':'Request S3 diagnostics for system information.';
 const grid=$('rangeGrid');grid.replaceChildren();const distances=s.native?.tofFront?.raw?.distanceMm;
 $('gridAge').textContent='Native snapshot age: '+(s.nativeAgeMs??'unknown')+' ms. Values are retained samples, not live range.';
 if(Array.isArray(distances)&&distances.length===64)for(const mm of distances){const cell=document.createElement('div');cell.textContent=mm;cell.style.cssText='padding:8px 2px;text-align:center;background:#284552;border-radius:4px';grid.append(cell);}
 show('firmwareJson',{c6:{version:g.firmware,slot:g.otaSlot,updating:g.otaUpdating},s3:s.system?{version:s.system.firmware,build:s.system.build,slot:s.system.otaSlot}:null});
 const event=`${g.transport} · UART ${g.uartAlive?'up':'down'} · Wi-Fi link ${g.wifiLinkAlive?'up':'down'} · S3 ${fresh?'live':'stale'}`;
 if(event!==lastEvent){lastEvent=event;events.push(new Date().toLocaleTimeString()+' '+event);events=events.slice(-60);$('events').textContent=events.join('\n');}
}
async function post(path,body,type='application/json'){const key=$('key').value.trim();if(key.length!==32){$('key').closest('details').open=true;$('key').focus();throw Error('Enter the maintenance key below.');}const response=await fetch(path,{method:'POST',headers:{'Content-Type':type,'X-Gladiator-Key':key},body:type==='application/json'?JSON.stringify(body):body});const text=await response.text();if(!response.ok)throw Error(text);return JSON.parse(text);}
async function action(id,work){try{await work();$(id).textContent='Request queued. S3 state confirms the result.';}catch(e){$(id).textContent=e.message;}}
const subscribe=()=>post('/api/subscribe',{intervalMs:1000,leaseMs:30000});
$('inspect').onclick=()=>action('detailReply',subscribe);document.querySelectorAll('[data-inspect]').forEach(b=>b.onclick=()=>action('detailReply',subscribe));$('systemInspect').onclick=()=>action('error',subscribe);
$('stream').onclick=()=>action('detailReply',async()=>{await subscribe();streaming=true;});$('endStream').onclick=()=>action('detailReply',async()=>{streaming=false;await post('/api/subscribe',{intervalMs:1000,leaseMs:0});});
setInterval(()=>{if(streaming&&!document.hidden)subscribe().catch(e=>{streaming=false;$('detailReply').textContent=e.message;});},15000);
$('ping').onclick=()=>action('linkReply',()=>post('/api/ping',{}));$('bulk').onclick=()=>action('linkReply',async()=>{await post('/api/link',{leaseMs:60000});await post('/api/subscribe',{intervalMs:100,leaseMs:60000});});
$('wifiForm').onsubmit=e=>{e.preventDefault();action('wifiReply',async()=>{await post('/api/config',{ssid:$('ssid').value,password:$('password').value});$('password').value='';});};
$('otaForm').onsubmit=async e=>{e.preventDefault();try{$('upload').disabled=true;const file=$('firmwareFile').files[0];const result=await post('/api/ota',await file.arrayBuffer(),'application/octet-stream');$('otaReply').textContent=result.message;}catch(e){$('otaReply').textContent=e.message;}finally{$('upload').disabled=false;}};
async function refresh(){try{const r=await fetch('/api/robot',{cache:'no-store',signal:AbortSignal.timeout(3000)});if(!r.ok)throw Error('HTTP '+r.status);draw(await r.json());$('error').textContent='';}catch(e){$('live').textContent='Gateway unreachable';draw({gateway:{robotConnected:false,transport:'none'},robot:{}});$('live').textContent='Gateway unreachable';$('error').textContent=e.message;}setTimeout(refresh,1000);}refresh();
</script></html>)HTML";
