"""Apply robot-frame metadata to the native chassis CAD; do not move hardware.

Run: PYTHONPATH=/usr/lib/freecad/lib python3 scripts/apply_mast_front_orientation.py
Head view is separately regenerated by build_head_master.py. Existing aliases,
released meshes/plates, and historical measurement labels remain unchanged.
"""
import json
import sys
from pathlib import Path
import FreeCAD as A

ROOT = Path('/home/buralien/projects/gladiator-cad')
FC = ROOT / 'cad/master/Gladiator_Master.FCStd'

def signature(shape):
    b = shape.BoundBox
    return [shape.Volume, shape.Area, len(shape.Solids), len(shape.Faces),
            b.XMin, b.XMax, b.YMin, b.YMax, b.ZMin, b.ZMax]

# Optional original native file preserves GUI styles when run inside FreeCAD.
source = Path(sys.argv[sys.argv.index('--preserve-view-source') + 1]) if '--preserve-view-source' in sys.argv else FC
doc = A.openDocument(str(source))
before = {o.Name: signature(o.Shape) for o in doc.Objects
          if hasattr(o, 'Shape') and not o.Shape.isNull() and o.Name != 'RobotFrontMarker'}
datum = doc.getObject('RobotOrientation') or doc.addObject('App::FeaturePython', 'RobotOrientation')
datum.Label = 'ROBOT FRAME: mast is FRONT (+Y), RIGHT +X, UP +Z'
for name, value in [('FrontVector', A.Vector(0, 1, 0)), ('RightVector', A.Vector(1, 0, 0)),
                    ('UpVector', A.Vector(0, 0, 1)), ('DeckOrigin', A.Vector(0, 0, 0))]:
    if name not in datum.PropertiesList:
        datum.addProperty('App::PropertyVector', name, 'Robot frame')
    setattr(datum, name, value)
for name, value in [('Orientation', 'MAST_FRONT'), ('DecisionDate', '2026-10-09'),
                    ('OriginMeaning', 'Rear-left lower deck corner'),
                    ('LegacyNames', 'Object IDs/parameter aliases and dated measurements retain mast-rear terms'),
                    ('HeadPose', 'Current head view: legacy pan180, tilt0; NOT centered home'),
                    ('CurrentHeadView', 'cad/head/master/Gladiator_Head_Master.FCStd'),
                    ('Documentation', 'docs/ORIENTATION.md')]:
    if name not in datum.PropertiesList:
        datum.addProperty('App::PropertyString', name, 'Robot frame')
    setattr(datum, name, value)
legacy_head = doc.getObject('HeadCandidate_v01')
if legacy_head:
    legacy_head.Label = 'Historical v01 head — use mast-front v05 head master for current view'

# Datum has no shape: never export orientation metadata as a manufactured part.
doc.Comment = (doc.Comment or '') + '\n2026-10-09: MAST_FRONT, +Y forward, +X right, +Z up; geometry unchanged. docs/ORIENTATION.md.'
doc.recompute()
doc.saveAs(str(FC))
A.closeDocument(doc.Name)
checked = A.openDocument(str(FC))
assert checked.RobotOrientation.FrontVector == A.Vector(0, 1, 0)
for name, old in before.items():
    new = signature(checked.getObject(name).Shape)
    assert all(abs(a-b) < 1e-5 for a, b in zip(old, new)), name
report = {'orientation': 'MAST_FRONT', 'front': [0, 1, 0], 'right': [1, 0, 0], 'up': [0, 0, 1],
          'origin': 'rear-left', 'original_shapes_checked': len(before),
          'all_geometry_unchanged': True, 'native_reload_checked': True,
          'step_geometry_unchanged': True, 'datum_nonmanufacturing': True}
(FC.parent / 'orientation.json').write_text(json.dumps(report, indent=2) + '\n')

# Refresh pose metadata beside the released head, without rerunning a large
# manufacturing/collision generator or changing historical validation results.
path = ROOT / 'cad/head/v05-sensor-mounts/head-config.json'
config = json.loads(path.read_text())
config['drive'].update({'robot_orientation': 'MAST_FRONT', 'robot_forward_cad_axis': '+Y',
                      'construction_pose_legacy_pan_deg': 0, 'mast_front_legacy_pan_deg': 180,
                      'mast_front_relative_travel_deg': [-200, 0], 'front_is_centered_home': False})
path.write_text(json.dumps(config, indent=2) + '\n')
print(json.dumps(report))
