"""Gladiator head master: a head-only FreeCAD file for looking at the mast head by itself.

Derived read-only from the current head prototype (cad/head/v05-sensor-mounts). Nothing is
modelled here: every solid is a copy of a v05 solid at its real robot position, so the file lines
up with Gladiator_Master.FCStd. Re-run this after the head prototype changes.

Run on the CAD server under a virtual display so the colours are saved:
    xvfb-run -a freecad scripts/build_head_master.py
"""
import json, os, sys, traceback
from pathlib import Path
import FreeCAD as A
import FreeCADGui as Gui

ROOT = Path('/home/buralien/projects/gladiator-cad')
SOURCE = ROOT / 'cad/head/v05-sensor-mounts/Gladiator_Head_v05_PanStack.FCStd'
OUT = ROOT / 'cad/head/master'
OUT.mkdir(parents=True, exist_ok=True)
NAME = 'Gladiator_Head_Master'
LOG = OUT / 'build.log'

# group -> (display colour, transparency %). Printed parts are opaque; hardware is see-through.
GROUPS = [
    ('FixedNeck', (0.78, 0.80, 0.84), 0),   # printed: neck, clamp cap, servo carriage
    ('Pan',       (0.95, 0.62, 0.25), 0),   # printed: rotor, retainer, pedestal, drive pulley
    ('Tilt',      (0.30, 0.65, 0.58), 0),   # printed: yoke, receiver, carrier, sensor frames, display frame
    ('Hardware',  (0.55, 0.58, 0.62), 55),  # bought parts and keep-out envelopes
]
SPECIAL = {  # per-object overrides inside Hardware
    'Dual_ToF_Envelope':   ((0.35, 0.50, 0.80), 78),
    'Dual_Radar_Envelope': ((0.80, 0.35, 0.35), 78),
    'ST7789_Board':        ((0.15, 0.20, 0.35), 40),
    'Pan_Belt_Reference':  ((0.10, 0.10, 0.10), 20),
    'SG90_Pan_Reference':  ((0.25, 0.45, 0.80), 55),
    'SG90_Tilt_Reference': ((0.25, 0.45, 0.80), 55),
}
CONTEXT = 'Ctx_MastTube'  # the only robot part kept, so the head sits on something

lines = []
def log(*a):
    s = ' '.join(str(x) for x in a)
    lines.append(s)
    LOG.write_text('\n'.join(lines) + '\n')

try:
    src = A.openDocument(str(SOURCE))
    doc = A.newDocument(NAME)
    doc.Comment = ('Head-only view of the Gladiator mast head. Generated by scripts/build_head_master.py '
                   'from cad/head/v05-sensor-mounts (read only). Real robot coordinates. '
                   'Do not edit by hand: change the head generators and re-run.')

    made = {}
    def copy_obj(name, label=None):
        o = src.getObject(name)
        n = doc.addObject('Part::Feature', name)
        n.Shape = o.Shape.copy()
        n.Label = label or o.Label
        made[name] = n
        return n

    group_members = {}
    for gname, color, transp in GROUPS:
        g = doc.addObject('App::DocumentObjectGroup', gname)
        sg = src.getObject(gname)
        names = [c.Name for c in sg.Group]
        group_members[gname] = names
        for nm in names:
            g.addObject(copy_obj(nm))
        made[gname] = g

    ctx = doc.addObject('App::DocumentObjectGroup', 'Mast_Context')
    ctx.addObject(copy_obj(CONTEXT, 'Mast_Tube (context, Z 6-130)'))
    made['Mast_Context'] = ctx
    doc.recompute()

    # colours (needs the GUI, which is why this runs under xvfb)
    for gname, color, transp in GROUPS:
        for nm in group_members[gname]:
            vo = made[nm].ViewObject
            c, t = SPECIAL.get(nm, (color, transp))
            vo.ShapeColor = c
            vo.Transparency = t
    mv = made[CONTEXT].ViewObject
    mv.ShapeColor = (0.85, 0.85, 0.85)
    mv.Transparency = 70

    fc = OUT / (NAME + '.FCStd')
    doc.saveAs(str(fc))
    log('saved', fc)

    # STEP alongside, same convention as the chassis master
    import Import
    leaves = [made[n] for g in group_members.values() for n in g] + [made[CONTEXT]]
    step = OUT / (NAME + '.step')
    Import.export(leaves, str(step))
    log('step', step, step.stat().st_size)

    # previews
    Gui.activateWorkbench('PartWorkbench')
    gd = Gui.getDocument(doc.Name)
    Gui.setActiveDocument(doc.Name)
    view = gd.ActiveView
    shots = {'iso': view.viewIsometric, 'front': view.viewFront, 'right': view.viewRight, 'rear': view.viewRear}
    for tag, fn in shots.items():
        fn()
        view.fitAll()
        p = OUT / ('preview-%s.png' % tag)
        view.saveImage(str(p), 1600, 1100, 'White')
        log('preview', p)

    # source integrity: counts and volumes must equal the source
    report = {}
    for gname, _, _ in GROUPS:
        for nm in group_members[gname]:
            a, b = src.getObject(nm).Shape, made[nm].Shape
            report[nm] = {'vol_src': round(a.Volume, 3), 'vol_new': round(b.Volume, 3),
                          'solids': len(b.Solids), 'valid': b.isValid()}
    (OUT / 'build-check.json').write_text(json.dumps(report, indent=1))
    bad = [k for k, v in report.items() if abs(v['vol_src'] - v['vol_new']) > 1e-6 or not v['valid']]
    log('parts', len(report), 'mismatch/invalid', bad)
    log('DONE')
except Exception:
    log('ERROR', traceback.format_exc())
finally:
    sys.stdout.flush()
    os._exit(0)
