"""Gladiator head master: a head-only FreeCAD file for looking at the mast head by itself.

Derived read-only from the current head prototype (cad/head/v05-sensor-mounts). Nothing is
modelled here: every solid is a copy of a v05 solid at its real robot position, so the file lines
up with Gladiator_Master.FCStd. Re-run this after the head prototype changes.

Run on the CAD server under a virtual display so the colours are saved:
    xvfb-run -a freecad scripts/build_head_master.py
"""
import json, math, os, sys, traceback
from pathlib import Path
import FreeCAD as A
import FreeCADGui as Gui

ROOT = Path('/home/buralien/projects/gladiator-cad')
SOURCE = ROOT / 'cad/head/v05-sensor-mounts/Gladiator_Head_v05_PanStack.FCStd'
OUT = ROOT / 'cad/head/master'
OUT.mkdir(parents=True, exist_ok=True)
NAME = 'Gladiator_Head_Master'
LOG = OUT / 'build.log'

# group -> (display colour, transparency %). Printed parts are opaque; hardware is see-through.
GROUPS = [
    ('FixedNeck', (0.78, 0.80, 0.84), 0),   # printed: neck, clamp cap, servo carriage
    ('Pan',       (0.95, 0.62, 0.25), 0),   # printed: rotor, retainer, pedestal, drive pulley
    ('Tilt',      (0.30, 0.65, 0.58), 0),   # printed: yoke, receiver, carrier, sensor frames, display frame
    ('Hardware',  (0.55, 0.58, 0.62), 55),  # bought parts and keep-out envelopes
]
SPECIAL = {  # per-object overrides inside Hardware
    'Dual_ToF_Envelope':   ((0.35, 0.50, 0.80), 78),
    'Dual_Radar_Envelope': ((0.80, 0.35, 0.35), 78),
    'ST7789_Board':        ((0.15, 0.20, 0.35), 40),
    'Pan_Belt_Reference':  ((0.10, 0.10, 0.10), 20),
    'SG90_Pan_Reference':  ((0.25, 0.45, 0.80), 55),
    'SG90_Tilt_Reference': ((0.25, 0.45, 0.80), 55),
}
CONTEXT = 'Ctx_MastTube'  # the only robot part kept, so the head sits on something
FRONT_PAN = 180.0  # existing checked endpoint; not a new centered servo home
PAN_CENTER = A.Vector(39.5, 113, 10)
SERVO_CENTER = PAN_CENTER + A.Vector(39.75 * math.cos(math.radians(225)),
                                    39.75 * math.sin(math.radians(225)), 0)

lines = []
def log(*a):
    s = ' '.join(str(x) for x in a)
    lines.append(s)
    LOG.write_text('\n'.join(lines) + '\n')

try:
    src = A.openDocument(str(SOURCE))
    doc = A.newDocument(NAME)
    doc.Comment = ('Head-only view of the Gladiator mast head. Generated by scripts/build_head_master.py '
                   'from cad/head/v05-sensor-mounts (read only). Real robot coordinates. '
                   'MAST_FRONT: +Y forward, +X right, +Z up. Displayed at legacy pan180/tilt0; '
                   'forward is a travel endpoint, not centered home. Do not edit by hand.')
    datum = doc.addObject('App::FeaturePython', 'RobotOrientation')
    datum.Label = 'FRONT = mast end (+Y); RIGHT +X; UP +Z'
    for name, vector in [('FrontVector', A.Vector(0, 1, 0)),
                         ('RightVector', A.Vector(1, 0, 0)), ('UpVector', A.Vector(0, 0, 1))]:
        datum.addProperty('App::PropertyVector', name, 'Robot frame')
        setattr(datum, name, vector)
    datum.addProperty('App::PropertyAngle', 'LegacyPanPose', 'Robot frame')
    datum.LegacyPanPose = FRONT_PAN
    datum.addProperty('App::PropertyString', 'TravelWarning', 'Robot frame')
    datum.TravelWarning = 'Legacy pan -20..180; mast-front relative -200..0. NOT centered home.'

    made = {}
    def copy_obj(name, label=None):
        o = src.getObject(name)
        n = doc.addObject('Part::Feature', name)
        shape = o.Shape.copy()
        motion = getattr(o, 'MotionGroup', 'fixed')
        if motion in ('pan', 'tilt'):
            shape.rotate(PAN_CENTER, A.Vector(0, 0, 1), FRONT_PAN)
        elif motion == 'servo':
            shape.rotate(SERVO_CENTER, A.Vector(0, 0, 1), FRONT_PAN / 1.5)
        n.Shape = shape
        n.addProperty('App::PropertyString', 'MotionGroup', 'Source')
        n.MotionGroup = motion
        n.Label = label or o.Label
        made[name] = n
        return n

    group_members = {}
    for gname, color, transp in GROUPS:
        g = doc.addObject('App::DocumentObjectGroup', gname)
        sg = src.getObject(gname)
        names = [c.Name for c in sg.Group]
        group_members[gname] = names
        for nm in names:
            g.addObject(copy_obj(nm))
        made[gname] = g

    ctx = doc.addObject('App::DocumentObjectGroup', 'Mast_Context')
    ctx.addObject(copy_obj(CONTEXT, 'Mast_Tube (context, Z 6-130)'))
    made['Mast_Context'] = ctx
    doc.recompute()

    # colours (needs the GUI, which is why this runs under xvfb)
    for gname, color, transp in GROUPS:
        for nm in group_members[gname]:
            vo = made[nm].ViewObject
            c, t = SPECIAL.get(nm, (color, transp))
            vo.ShapeColor = c
            vo.Transparency = t
    mv = made[CONTEXT].ViewObject
    mv.ShapeColor = (0.85, 0.85, 0.85)
    mv.Transparency = 70

    fc = OUT / (NAME + '.FCStd')
    doc.saveAs(str(fc))
    log('saved', fc)

    # STEP alongside, same convention as the chassis master
    import Import
    leaves = [made[n] for g in group_members.values() for n in g] + [made[CONTEXT]]
    step = OUT / (NAME + '.step')
    Import.export(leaves, str(step))
    log('step', step, step.stat().st_size)

    # previews
    Gui.activateWorkbench('PartWorkbench')
    gd = Gui.getDocument(doc.Name)
    Gui.setActiveDocument(doc.Name)
    view = gd.ActiveView
    # FreeCAD standard front looks from -Y, now the robot's REAR.
    shots = {'iso': view.viewIsometric, 'front': view.viewRear, 'right': view.viewRight, 'rear': view.viewFront}
    for tag, fn in shots.items():
        fn()
        view.fitAll()
        p = OUT / ('preview-%s.png' % tag)
        view.saveImage(str(p), 1600, 1100, 'White')
        log('preview', p)

    # source integrity: counts and volumes must equal the source
    report = {}
    for gname, _, _ in GROUPS:
        for nm in group_members[gname]:
            a, b = src.getObject(nm).Shape, made[nm].Shape
            report[nm] = {'vol_src': round(a.Volume, 3), 'vol_new': round(b.Volume, 3),
                          'solids': len(b.Solids), 'valid': b.isValid(),
                          'motion': made[nm].MotionGroup}
    (OUT / 'build-check.json').write_text(json.dumps(report, indent=1))
    bad = [k for k, v in report.items() if abs(v['vol_src'] - v['vol_new']) > 1e-6 or not v['valid']]
    # Check the native artifact, not only the in-memory model.
    A.closeDocument(doc.Name)
    checked = A.openDocument(str(fc))
    assert checked.RobotOrientation.FrontVector == A.Vector(0, 1, 0)
    for nm in report:
        assert checked.getObject(nm).Shape.isValid(), nm
        assert abs(checked.getObject(nm).Shape.Volume - src.getObject(nm).Shape.Volume) < 1e-5, nm
        if report[nm]['motion'] in ('fixed', 'belt'):
            # Bounding boxes can change slightly when GUI tessellation caches
            # are rebuilt; compare exact placement and vertices instead.
            a, b = src.getObject(nm).Shape, checked.getObject(nm).Shape
            assert (a.Placement.Base - b.Placement.Base).Length < 1e-9, nm
            assert abs(abs(sum(x*y for x,y in zip(a.Placement.Rotation.Q, b.Placement.Rotation.Q)))-1) < 1e-9, nm
            assert len(a.Vertexes) == len(b.Vertexes), nm
            assert all((va.Point-vb.Point).Length < 1e-6 for va,vb in zip(a.Vertexes,b.Vertexes)), nm
    assert checked.Dual_ToF_Envelope.Shape.BoundBox.Center.y > 113, 'sensor must face mast-front +Y'
    assert not bad, bad
    (OUT / 'orientation.json').write_text(json.dumps({
        'orientation': 'MAST_FRONT', 'front': [0, 1, 0], 'right': [1, 0, 0], 'up': [0, 0, 1],
        'legacy_pan_pose_deg': FRONT_PAN, 'legacy_travel_deg': [-20, 180],
        'front_relative_travel_deg': [-200, 0], 'centered_home': False,
        'source_print_geometry_changed': False, 'native_reload_checked': True}, indent=2) + '\n')
    log('parts', len(report), 'mismatch/invalid', bad)
    log('DONE')
except Exception:
    log('ERROR', traceback.format_exc())
finally:
    sys.stdout.flush()
    os._exit(0)
