#pragma once
// S3-only recovery. Normal development belongs to C6 /dev.
static const char SERVICE_PAGE[]=R"HTML(<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gladiator · Recovery service</title>
<style>:root{color-scheme:dark;font-family:system-ui}*{box-sizing:border-box}body{max-width:800px;margin:auto;padding:24px;background:#0c131a;color:#eaf1f5}section{background:#17232d;border-radius:12px;padding:20px;margin:18px 0}small,p{color:#a6b8c4}a{color:#82d6ec}button,input{font:inherit;padding:12px;max-width:100%}button{background:#e8ad42;border:0;border-radius:8px;color:#111}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:400px;overflow:auto;background:#0c131a;padding:16px}details{padding:12px 0}summary{cursor:pointer}#state{font-size:28px;font-weight:700}output{display:block;margin:12px 0}</style>
<h1>Gladiator recovery service</h1><small>Interface v1 · Direct S3 access</small><p>Use this service for recovery, firmware maintenance and fault evidence. Normal development and testing live on the C6 <a href="http://192.168.8.1/dev">development interface</a>.</p>
<section><h2>Recovery status</h2><div id="state">UNKNOWN</div><p id="status">Connecting to S3…</p><button id="stop">DISARM</button><output id="reply" role="status"></output><details><summary>Boot, power and recovery details</summary><pre id="system"></pre></details></section>
<section><h2>S3 firmware</h2><p>Upload the S3 firmware.bin image. Starting an update disarms and coasts both motors. USB remains the independent recovery path.</p><form method="POST" action="/update" enctype="multipart/form-data"><input type="file" name="firmware" accept=".bin" required aria-label="S3 firmware image"> <button>Upload and reboot S3</button></form></section>
<section><h2>Recovery tools</h2><details><summary>Retained S3 log</summary><button id="readLogs">Read logs</button><pre id="logs">Not requested</pre></details><details><summary>Native fault evidence</summary><p><a href="/api/sensors" target="_blank">Complete S3 sensor snapshot</a></p><p><a href="/api/gateway" target="_blank">S3 communications diagnostics</a></p><p><a href="/api/status" target="_blank">S3 recovery status JSON</a></p></details><details><summary>Fallback field access</summary><p>Use when the C6 is unavailable. The same field interface requires explicit arming and expires interrupted sessions.</p><a href="/field">Open recovery field controls</a></details></section>
<script>
const $=id=>document.getElementById(id);
async function get(path){const r=await fetch(path,{cache:'no-store',signal:AbortSignal.timeout(2000)});if(!r.ok)throw Error('HTTP '+r.status);return r;}
async function refresh(){try{const s=await (await get('/api/status')).json();$('state').textContent=s.state||'UNKNOWN';$('status').textContent='Battery '+(s.battery||'UNKNOWN')+' · '+(s.powerSource||'UNKNOWN')+' · Last reset '+(s.resetReason||'UNKNOWN');$('system').textContent=JSON.stringify(s,null,2);}catch(e){$('state').textContent='UNKNOWN';$('status').textContent='S3 unavailable';}setTimeout(refresh,1000);}
$('stop').onclick=async()=>{try{const r=await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'command=disarm',signal:AbortSignal.timeout(2000)});$('reply').textContent=await r.text();}catch(e){$('reply').textContent='DISARM not confirmed: '+e.message;}};
$('readLogs').onclick=async()=>{try{$('logs').textContent=await (await get('/api/logs')).text();}catch(e){$('logs').textContent=e.message;}};refresh();
</script></html>)HTML";
